# Northwind Traders — Data Exploration Notebook

**Goal:** Explore the Northwind data from Python/Jupyter (instead of pgAdmin) using the Dockerized PostgreSQL database.

**Connection facts (from our DE setup):**
- DB engine = PostgreSQL in Docker (`northwind_db`)
- Host port `55432` maps to the container's `5432`
- user `postgres` / password `postgres` / db `northwind`
- Our Python packages: `psycopg` (Postgres driver) + `pandas` (data frames)

**Workflow split:**
- **pgAdmin** (`http://localhost:5050`) → manage the database, browse schema, save `.sql` files.
- **This notebook** → explore data: write SQL, see results as DataFrames, iterate quickly.

In [16]:
import psycopg
import pandas as pd

# --- Connection ---
# One process-wide connection. psycopg uses libpq under the hood (the official
# Postgres C client), so this is the closest you can get to "raw Postgres" in
# Python without writing C.
CONN = psycopg.connect(
    "postgresql://postgres:postgres@localhost:55432/northwind",
    autocommit=True,   # each query commits immediately — simpler for exploration
)

def run_query(sql, params=None):
    """Run a SQL query and return the result as a pandas DataFrame.

    Note: pandas prefers SQLAlchemy connections, but psycopg's `Connection`
    supports the same DBAPI interface (PEP 249). We fetch rows into a list of
    tuples with the column names, then build the DataFrame ourselves — this
    avoids the SQLAlchemy `UserWarning` and stays closer to raw Postgres.
    """
    with CONN.cursor() as cur:
        cur.execute(sql, params)
        rows = cur.fetchall()
        cols = [d.name for d in cur.description] if cur.description else []
    return pd.DataFrame(rows, columns=cols)

## 1. Sanity check — are we connected?

Count rows in a few key tables to confirm the data is loaded.

In [17]:
run_query("""
SELECT 'orders'         AS tbl, count(*) AS n FROM orders
UNION ALL SELECT 'customers',    count(*) FROM customers
UNION ALL SELECT 'products',     count(*) FROM products
UNION ALL SELECT 'employees',    count(*) FROM employees
UNION ALL SELECT 'categories',   count(*) FROM categories
UNION ALL SELECT 'order_details',count(*) FROM order_details
ORDER BY tbl;
""")

             tbl     n
0     categories     8
1      customers    91
2      employees     9
3  order_details  2155
4         orders   830
5       products    77

## 2. Exploring the Northwind Database - Getting to Know the Data

**The grain (declared once, used everywhere):**

> One row in `order_details` = one product sold inside one order.
> Grain key: `(order_id, product_id)`.

If a customer buys 3 different products in one order → 3 rows in `order_details`.
If they buy 5 units of the same product in one order → 1 row with `quantity = 5`.

This is the **fact table** of our (snowflake) star schema. Every analytic question we
ask will slice this grain by joining to one or more **dimension tables**: `customers`,
`employees`, `products`, `categories`, `shippers`, `suppliers`.

In [18]:
run_query("""
    SELECT 
        table_name as name,
        table_type as type
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_type IN ('BASE TABLE', 'VIEW') 
""")

                      name        type
0              territories  BASE TABLE
1            order_details  BASE TABLE
2     employee_territories  BASE TABLE
3                us_states  BASE TABLE
4                customers  BASE TABLE
5                   orders  BASE TABLE
6                employees  BASE TABLE
7                 shippers  BASE TABLE
8                 products  BASE TABLE
9               categories  BASE TABLE
10               suppliers  BASE TABLE
11                  region  BASE TABLE
12   customer_demographics  BASE TABLE
13  customer_customer_demo  BASE TABLE

In [19]:
run_query("SELECT * FROM customers LIMIT 5")

,customer_id,company_name,contact_name,contact_title,address,city,region,postal_code,country,phone,fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,None,12209,Germany,030-0074321,030-0076545
1,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,None,05021,Mexico,(5) 555-4729,(5) 555-3745
2,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,None,05023,Mexico,(5) 555-3932,NaN
3,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,None,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
4,BERGS,Berglunds snabbköp,Christina Berglund,Order Administrator,Berguvsvägen 8,Luleå,None,S-958 22,Sweden,0921-12 34 65,0921-12 34 67

In [20]:
run_query("SELECT * FROM orders LIMIT 5")

,order_id,customer_id,employee_id,order_date,required_date,shipped_date,ship_via,freight,ship_name,ship_address,ship_city,ship_region,ship_postal_code,ship_country
0,10248,VINET,5,1996-07-04,1996-08-01,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
1,10249,TOMSP,6,1996-07-05,1996-08-16,1996-07-10,1,11.61,Toms Spezialitäten,Luisenstr. 48,Münster,NaN,44087,Germany
2,10250,HANAR,4,1996-07-08,1996-08-05,1996-07-12,2,65.83,Hanari Carnes,"Rua do Paço, 67",Rio de Janeiro,RJ,05454-876,Brazil
3,10251,VICTE,3,1996-07-08,1996-08-05,1996-07-15,1,41.34,Victuailles en stock,"2, rue du Commerce",Lyon,NaN,69004,France
4,10252,SUPRD,4,1996-07-09,1996-08-06,1996-07-11,2,51.30,Suprêmes délices,"Boulevard Tirou, 255",Charleroi,NaN,B-6000,Belgium

In [21]:
# Verify the declared grain: every (order_id, product_id) pair must be unique.
# If this returns 0 rows, the grain holds. If it returns rows, we have duplicates
# and the grain is wrong (or the table has bad data).
run_query("""
    SELECT order_id, product_id, COUNT(*) AS n
    FROM order_details
    GROUP BY order_id, product_id
    HAVING COUNT(*) > 1;
""")

Empty DataFrame
Columns: [order_id, product_id, n]
Index: []

In [22]:
# Combine orders and employees tables to see who is responsible for each order
run_query("""
    SELECT 
        e.first_name || ' ' || e.last_name AS employee_name,
        o.order_id,
        o.order_date
    FROM orders o
    JOIN employees e ON o.employee_id = e.employee_id
    LIMIT 10;
""")

      employee_name  order_id  order_date
0   Steven Buchanan     10248  1996-07-04
1    Michael Suyama     10249  1996-07-05
2  Margaret Peacock     10250  1996-07-08
3   Janet Leverling     10251  1996-07-08
4  Margaret Peacock     10252  1996-07-09
5   Janet Leverling     10253  1996-07-10
6   Steven Buchanan     10254  1996-07-11
7    Anne Dodsworth     10255  1996-07-12
8   Janet Leverling     10256  1996-07-15
9  Margaret Peacock     10257  1996-07-16

In [23]:
# Combine orders and customers tables to get more detailed information about each customer:
run_query("""
    SELECT 
        o.order_id,
        c.company_name,
        c.contact_name,
        o.order_date
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    LIMIT 10;
    
""")

   order_id               company_name      contact_name  order_date
0     10248  Vins et alcools Chevalier      Paul Henriot  1996-07-04
1     10249         Toms Spezialitäten     Karin Josephs  1996-07-05
2     10250              Hanari Carnes      Mario Pontes  1996-07-08
3     10251       Victuailles en stock      Mary Saveley  1996-07-08
4     10252           Suprêmes délices  Pascale Cartrain  1996-07-09
5     10253              Hanari Carnes      Mario Pontes  1996-07-10
6     10254          Chop-suey Chinese         Yang Wang  1996-07-11
7     10255         Richter Supermarkt      Michael Holz  1996-07-12
8     10256     Wellington Importadora     Paula Parente  1996-07-15
9     10257           HILARION-Abastos  Carlos Hernández  1996-07-16

In [24]:
# Combine order_details, products, and orders to get detailed order information including the product name and quantity
run_query("""
    SELECT 
        o.order_id,
        p.product_name,
        od.quantity,
        o.order_date
    FROM order_details od
    JOIN products p ON od.product_id = p.product_id
    JOIN orders o ON od.order_id = o.order_id
    LIMIT 10;
""")

   order_id                      product_name  quantity  order_date
0     10248                    Queso Cabrales        12  1996-07-04
1     10248     Singaporean Hokkien Fried Mee        10  1996-07-04
2     10248            Mozzarella di Giovanni         5  1996-07-04
3     10249                              Tofu         9  1996-07-05
4     10249             Manjimup Dried Apples        40  1996-07-05
5     10250   Jack's New England Clam Chowder        10  1996-07-08
6     10250             Manjimup Dried Apples        35  1996-07-08
7     10250  Louisiana Fiery Hot Pepper Sauce        15  1996-07-08
8     10251               Gustaf's Knäckebröd         6  1996-07-08
9     10251                    Ravioli Angelo        15  1996-07-08

## 3. Rank employees by sales performance

In [32]:
run_query("""
    WITH employeeSales AS(
        SELECT 
        e.employee_id,
        e.first_name,
        e.last_name,
        SUM(od.unit_price * od.quantity * (1 - od.discount)) AS Total_Sales
        FROM orders o
            JOIN order_details od ON o.order_id = od.order_id
            JOIN employees e ON e.employee_id = o.employee_id
        GROUP BY e.employee_id
    )
        SELECT 
            employee_id,
            first_name,
            last_name,
            RANK() OVER (ORDER BY Total_Sales DESC) AS Sales_Rank
        FROM employeeSales
""")

   employee_id first_name  last_name  sales_rank
0            4   Margaret    Peacock           1
1            3      Janet  Leverling           2
2            1      Nancy    Davolio           3
3            2     Andrew     Fuller           4
4            8      Laura   Callahan           5
5            7     Robert       King           6
6            9       Anne  Dodsworth           7
7            6    Michael     Suyama           8
8            5     Steven   Buchanan           9

## 4. Calculate running total of sales per month

In [38]:
run_query("""
    WITH monthlySales AS(
        SELECT 
            DATE_TRUNC('month', order_date) AS month,
            SUM(od.unit_price * od.quantity * (1 - od.discount)) AS Total_Sales
        FROM orders o 
        INNER JOIN order_details od ON o.order_id = od.order_id
        GROUP BY DATE_TRUNC('month', order_date)
    )
        SELECT *
        FROM monthlySales
""")

                       month    total_sales
0  1996-12-01 00:00:00+00:00   45239.630493
1  1996-10-01 00:00:00+00:00   37515.724945
2  1997-06-01 00:00:00+00:00   36362.802335
3  1996-11-01 00:00:00+00:00   45600.045211
4  1998-03-01 00:00:00+00:00  104854.155000
5  1997-08-01 00:00:00+00:00   47287.669688
6  1997-02-01 00:00:00+00:00   38483.634950
7  1998-05-01 00:00:00+00:00   18333.630432
8  1996-07-01 00:00:00+00:00   27861.895130
9  1996-08-01 00:00:00+00:00   25485.275071
10 1997-01-01 00:00:00+00:00   61258.070168
11 1997-11-01 00:00:00+00:00   43533.808768
12 1997-09-01 00:00:00+00:00   55629.242402
13 1997-04-01 00:00:00+00:00   53032.952389
14 1997-07-01 00:00:00+00:00   51020.857519
15 1997-10-01 00:00:00+00:00   66749.225776
16 1997-12-01 00:00:00+00:00   71398.428464
17 1998-01-01 00:00:00+00:00   94222.110207
18 1996-09-01 00:00:00+00:00   26381.400133
19 1998-02-01 00:00:00+00:00   99415.287383
20 1997-03-01 00:00:00+00:00   38547.220110
21 1998-04-01 00:00:00+00:00  123798.682256
22 1997-05-01 00:00:00+00:00   53781.289825